### ISSUE TITLE
[Bug] problem in styling.js

### ISSUE THREAD

**Issue by xdy** [ChasarooniZ/pf2e-usage-updater#15]
Got an undefined error in pf2e-usage-updater when playing last night, didn't dig into it, just did a quick patch which made it stop throwing errors. There's probably a better fix.
I changed styling.js line 77 to:
```
            return `${largestUnit?.remainder > 0 ? '< ' : ""}${largestUnit?.remainder > 0 ? largestUnit?.count + 1 : largestUnit?.count} ${largestUnit?.name.charAt(0)}`;
```

**Comment by ChasarooniZ** [comment]
<3
